CUDA_VISIBLE_DEVICES=2 python cv_run_ner.py \
                        --data_dir data/semeval2017/data_with_pronunciation/pl-hete/\
                        --bert_model /home/lawson/pretrain/bert-base-cased\
                        --task_name ner \
                        --output_dir out \
                        --max_seq_length 55 \
                        --do_train \
                        --num_train_epochs 10 \
                        --train_batch_size 32 \
                        --eval_batch_size 5 \
                        --file_suffix "2021_0713_50" \
                        --use_sense \
                        --do_pron \
                        --defi_num 50